version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reflection
    ports:
      - "5432:5432"
    networks:
      - my-network

  redis:
    image: redis:7.2
    container_name: my-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - my-network
    environment:
      SPRING_REDIS_HOST: redis

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # 給應用程式連線
      - "15672:15672"     # 管理介面（Web UI）
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  spring-app:
    build: .
    container_name: my-spring-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reflection
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SERVER_PORT: 8080
    

    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - ./config/application.properties:/app/config/application.properties



networks:
  my-network: